/**
 * Minimal IManageableVault ABI used by curator pages.
 */
export const manageableVaultAbi = [
  {
    type: "function",
    name: "mTokenDataFeed",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "feeReceiver",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "tokensReceiver",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "instantDailyLimit",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "instantFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "requestRedeemer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "setTokensReceiver",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "receiver" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeReceiver",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "receiver" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setRequestRedeemer",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "redeemer" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setInstantFee",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "newInstantFee" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setInstantDailyLimit",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "newInstantDailyLimit" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setVariationTolerance",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "tolerance" }],
    outputs: [],
  },
  {
    type: "function",
    name: "variationTolerance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "addPaymentToken",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "address", name: "dataFeed" },
      { type: "uint256", name: "fee" },
      { type: "uint256", name: "allowance" },
      { type: "bool", name: "stable" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawToken",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "amount" },
      { type: "address", name: "withdrawTo" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getPaymentTokens",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]", name: "" }],
  },
  {
    type: "function",
    name: "tokensConfig",
    stateMutability: "view",
    inputs: [{ type: "address", name: "token" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { type: "address", name: "dataFeed" },
          { type: "uint256", name: "fee" },
          { type: "uint256", name: "allowance" },
          { type: "bool", name: "stable" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "removePaymentToken",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "changeTokenFee",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "fee" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeTokenAllowance",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "allowance" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "safeBulkApproveRequestAtSavedRate",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256[]", name: "requestIds" }],
    outputs: [],
  },
  {
    type: "function",
    name: "safeBulkApproveRequest",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256[]", name: "requestIds" }],
    outputs: [],
  },
  {
    type: "function",
    name: "safeBulkApproveRequest",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256[]", name: "requestIds" },
      { type: "uint256", name: "newMTokenRate" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "safeApproveRequest",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "requestId" },
      { type: "uint256", name: "newMTokenRate" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "approveRequest",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "requestId" },
      { type: "uint256", name: "newMTokenRate" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rejectRequest",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [],
  },
  /** RedemptionVault: `mapping(uint256 => Request) public redeemRequests` */
  {
    type: "function",
    name: "redeemRequests",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [
      { type: "address", name: "sender" },
      { type: "address", name: "tokenOut" },
      { type: "uint8", name: "status" },
      { type: "uint256", name: "amountMToken" },
      { type: "uint256", name: "mTokenRate" },
      { type: "uint256", name: "tokenOutRate" },
    ],
  },
  /** DepositVault: `mapping(uint256 => Request) public mintRequests` */
  {
    type: "function",
    name: "mintRequests",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "requestId" }],
    outputs: [
      { type: "address", name: "sender" },
      { type: "address", name: "tokenIn" },
      { type: "uint8", name: "status" },
      { type: "uint256", name: "depositedUsdAmount" },
      { type: "uint256", name: "usdAmountWithoutFees" },
      { type: "uint256", name: "tokenOutRate" },
    ],
  },
] as const;
